### ISSUE TITLE
RFC: Portability of reference images

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/MakieGallery.jl#55]
We currently download reference images for visual regression tests from Github.  

However, this is annoying for two reasons:

1) It requires an internet connection

2) It precludes the possibility of using a custom set of reference images

I propose that we could fix this by reading an environment variable `MAKIEGALLERY_REFIMG_PATH` to indicate a path for the reference image directory while testing.  If that environment variable does not exist (i.e., `!haskey(ENV, "MAKIEGALLERY_REFIMG_PATH")`), then we redownload the reference images and indicate that in stdout, as well as (possibly) saving the path for future use (or creating it as a git repo and `git pull --force`ing it every test.

**Comment by heitorPB** [comment]
Where do I get those ReferenceImages? I'm trying to compile the docs here but it fails exactly there.

Currently `docs/make.jl:15` looks for it in `mediapath = joinpath(homedir(), "ReferenceImages", "gallery")`

**Comment by asinghvi17** [comment]
SimonDanisch/ReferenceImages

**Comment by heitorPB** [comment]
Why not move the ReferenceImages to this repository?

CC @SimonDanisch

**Comment by SimonDanisch** [comment]
Because it's a huge repository with it's own release cycle. The release cycle already makes it a no-go to include it here, but if it wasn't, the other point is equally important: MakieGallery shouldn't be 340mb, since it can also used without actually comparing to the reference images!

**Comment by heitorPB** [comment]
I came up to this repo because I wanted to add a few things to Makie Docs. But after a week trying to understand how Makie is organized, I still don't get it.

If I understood it:
- JuliaPlots/Makie.jl: the metapackage for ploting.
- JuliaPlots/MakieGallery.jl: a gallery of images and the documentation of Makie
- SimonDanisch/ReferenceImages: another gallery of images needed to build the documentation.

Why there's two repos for a gallery of examples?

My suggestion:
- move the docs to JuliaPlots/MakieDocs.jl
- refacor SimonDanisch/ReferenceImages so it creates the images when needed (e.g. with `julia make.jl`), this way the repo will not be 340 mb.
- Move Ref Images to the MakeDocs.jl repository, under a section/chapter `Examples` or `Gallery`, in a similar way of [MatPlotLib's Gallery](https://matplotlib.org/gallery/index.html)

This would make the life of random people wanting to help easier.
